- appveyor.yml
- setup.py
Sets up Windows Python builds using AppVeyor
See COMPUTE-29
> CI for Python on Windows

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
- src/bindings/bnd_layer.cpp
- src/bindings/bnd_layer.h
- src/bindings/bnd_object.cpp
* Get/Set name
* Get Id
* Get ParentLayerId
> Add crude ON_Layer access.

- samples/javascript/compute.rhino3d.js
Update to the javascript client library for compute to support batch calls
Cite COMPUTE-47
> Add support for batch calls

- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
> Create MeshingParameters Bindings

- src/bindings/bnd_point.cpp
Cite COMPUTE-52
Cite COMPUTE-55
> add encode functions for points and vectors

- src/bindings/bnd_defines.cpp
- src/bindings/bnd_point.cpp
- src/bindings/bnd_revsurface.cpp
- src/bindings/bnd_revsurface.h
Fixes COMPUTE-52
Fixes COMPUTE-53
Fixes COMPUTE-54
Fixes COMPUTE-55
> Fix Point3d.Unset, add LoftType, add RevSurface.Create

- samples/javascript/compute.rhino3d.js
> Add version and user agent to client lib

- setup.py
- src/bindings/bnd_boundingbox.h
- src/bindings/bnd_nurbssurface.cpp
- src/bindings/bnd_nurbssurface.h
- src/bindings/bnd_object.cpp
- src/bindings/bnd_object.h
- src/bindings/bnd_xform.cpp
- src/bindings/bnd_xform.h
- src/rhino3dm/__init__.py
Part of COMPUTE-61 being done to allow python script evaluation on the compute server
> Add serialzation of dict using ArchivableDictionary

- src/bindings/bnd_object.cpp
- src/bindings/bnd_object.h
> python support geometry array in ArchivableDictionary

- src/build_javascript_lib.py
See https://stackoverflow.com/questions/6466711/what-is-the-return-value-of-os-system-in-python
> Extract proper return code from os.system()

- setup.py
- src/bindings/bnd_arccurve.cpp
- src/bindings/bnd_arccurve.h
- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_viewport.cpp
- src/bindings/bnd_viewport.h
- src/rhino3dm/__init__.py
> Update OpenNURBS and add a few more funcs

- setup.py
- src/bindings/bnd_viewport.cpp
- src/bindings/bnd_viewport.h
- src/rhino3dm/__init__.py
> Add viewport screensize and frustum functions

- setup.py
- src/bindings/bindings.cpp
- src/rhino3dm/__init__.py
> Try to implement RenderSettings the correct way

- .circleci/config.yml
- src/build_dotnet.py
Adds a CI build for dotnet running in an Ubuntu 18.04 docker container on CircleCI
Fixes RH3DM-25
> CI for dotnet (and improved performance)

- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_point.cpp
python support for Point2f, Vector3f, MeshNormalsList & MeshTextureCoordinateList iterators.
> pybindings

- samples/javascript/RESTHopper/Extrusions/BranchNodeRnd.ghx
- samples/javascript/RESTHopper/Extrusions/index.html
Making inputs wider and transparent over canvas.
> Updating Definition and index

- setup.py
As discussed in https://github.com/mcneel/rhino3dm/pull/106
Construct loop more succinctly and pythonically :snake:
> Update code example in setup.py

- .gitignore
- README.md
- docs/dotnet/RHINO3DM-BUILD.CS.md
- docs/javascript/RHINO3DM.JS.md
- docs/python/RHINO3DM.PY.md
- src/build_dotnet.py
- src/methodgen/methodgen.csproj
> Add .NET compile instructions

- src/bindings/bnd_extensions.cpp
> fix options to allow for other versions

- src/bindings/bnd_extensions.cpp
> fix layer addition routine

- docs/javascript/samples/viewer/01_basic/index.html
- docs/javascript/samples/viewer/02_advanced/hello_mesh_pbr.html
- docs/javascript/samples/viewer/02_advanced/index.html
- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
> Add overload for toThreejsJSON

- docs/javascript/RHINO3DM-BUILD.JS.md
Add note about bootstrap and correct some obsolete info.
> Update javascript build instructions.

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
- src/bindings/bnd_nurbssurface.cpp
also fixes NurbsCurveKnotList duplication in javascript
> cache object list for indexing

- Current Development Tools.md
- docs/javascript/RHINO3DM-BUILD.JS.md
- script/bootstrap.py
bootstrap.py detects the version of python you are running and reports accordingly.
> bootstrap: separate python 2 and 3

- script/bootstrap.py
- script/build.py
- script/setup.py
Saying these scripts actually adhere is not accurate.
> Be honest about Scripts-to-rule-them-all

- Current Development Tools.md
- script/bootstrap.py
Also change wording in Emscripten path instructions.  Cite RH3DM-70.
> Fix a path bug in bootstrap.

- Current Development Tools.md
- script/README.md
- script/bootstrap.py
Stub out README.md for scripts folder as well.
> Add bootstrap checks for iOS

- Current Development Tools.md
- script/build.py
Add initial support for librhino3dm(io)_native.a builds for iOS.  Fixes RH3DM-79
> Initial support for ios builds

- Current Development Tools.md
- script/bootstrap.py
> Add bootstrap checks for android

- script/setup.py
- src/librhino3dmio_native/CMakeLists.txt
Cite RH3DM-80.  Still more work remains.
> First pass at Android setup

- Current Development Tools.md
- script/setup.py
Also update current NKD.  Cite RH3DM-80
> Use bootstrap to find NDK path

- script/setup.py
> setup.py for multiple android ABIs

- script/build.py
> Check for success or failure

- script/setup.py
- src/dotnet/Rhino3dm.Android.csproj
Rhino3dm.Android.csproj uses librhino3dmio_native.so.
Fixes RH3DM-82
> Rhino3dm.Android.csproj

- script/README.md
to reflect the current state-of-affairs.  Lots of TODOs remain.
> Update the script README

- Current Development Tools.md
- script/bootstrap.py
> bootstrap.py -p windows working

- script/bootstrap.py
- script/setup.py
- src/librhino3dm_native/CMakeLists.txt
Initial support for windows builds in setup script.
> setup.py -p windows

- script/build.py
- script/setup.py
- src/librhino3dm_native/CMakeLists.txt
Initial support for librhino3dm_native on Windows.
> build.py -p windows

- script/build.py
- script/setup.py
A bunch of Don't Repeat Yourself housekeeping
> DRY: Housekeeping

- Current Development Tools.md
- script/bootstrap.py
- script/build.py
- script/setup.py
> Add script support for linux builds

- script/bootstrap.py
> Use emcc --version to get emscripten version

- script/README.md
Android builds on linux are very difficult to support.
> Linux desktop complete

- script/bootstrap.py
> Check to make sure EMSDK is set

- script/setup.py
Requires cmake 3.14
See https://cmake.org/cmake/help/v3.14/release/3.14.html
> Generate vs2019 project files

- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_object.cpp
- src/bindings/bnd_subd.cpp
- src/bindings/bnd_subd.h
Subdivide and GetControlNetMesh for SubD
Part of #304
> Bindings for SubD::Subdivide GetControlNetMesh

- src/bindings/bnd_brep.cpp
- src/bindings/bnd_object.cpp
> improve pointer tracking

- src/bindings/bnd_brep.cpp
- src/bindings/bnd_brep.h
> add DuplicateFace and DuplicateSurface functions

- src/bindings/bnd_xform.cpp
- src/bindings/bnd_xform.h
> Add Transform functions

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
> Add GroupMembers function to group table in python

- src/CMakeLists.txt
> remove html from compile output

- src/dotnet/Rhino3dm.core.csproj
- src/dotnet/build/net45/Rhino3dm.props
> Include win32 native lib in nuget package

- src/bindings/bnd_object.cpp
- src/bindings/bnd_object.h
> Add CommonObject::IsValid wrapper

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
> Add AddLayer to File3dm

- src/bindings/bnd_surface.cpp
- src/bindings/bnd_surface.h
Added binding function for ON_Surface::FrameAt(). CI built and I tested the js artifacts and for back the tuple result.
> Bindings: Surface FrameAt()

- src/bindings/bnd_3dm_settings.cpp
- src/bindings/bnd_3dm_settings.h
- src/bindings/bnd_defines.cpp
> earth anchor implementation

- src/bindings/bnd_circle.cpp
- src/bindings/bnd_circle.h
- src/bindings/bnd_light.cpp
- src/bindings/bnd_light.h
- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_sphere.cpp
- src/bindings/bnd_sphere.h
- BND_Sphere::ClosestParameter()
- BND_Circle::ClosestParameter()
- BND_Light::GetSpotLightRadii()
- BND_MeshFaceList::GetFaceVertices()
- BND_MeshFaceList::GetFaceCenter()
> Adding Some Bindings

- .github/workflows/workflow_release.yml
- docs/publishing.md
Packages dotnet windows, linux, and macos builds into one nupkg and creates an artifact that can be used to push a new version.
> Adding dotnet pack

- .github/workflows/workflow_ci.yml
- .github/workflows/workflow_release.yml
- src/create_python_vcxproj.py
> Revert "update python to build against VS2022"

- docs/python/RHINO3DM.PY.md
The old link wasn't working anymore, added the new one.
> Added new pip install link

- src/bindings/bnd_brep.cpp
- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_pointcloud.cpp
> pybind11 likes iterators to throw when they are done

- script/codesign-native.sh
I'm not kidding: run `man codesign`
> Be extremely verbose

- CHANGELOG.md
- src/bindings/bnd_polyline.cpp
- src/bindings/bnd_polyline.h
Fixed Polyline.CreateFromPoints by using BND_Point3dList as input
> Fixed Polyline.CreateFromPoints method cite #616
