mcneel/rhino3dm

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
The tables supported are Layers, Materials
Objects and Views.
* Introduce a templated iterator struct
* Add FindIndex() helper functions to tables that
don't have them yet
More tables can be added as necessary.
> Add __iter__ support for tables.

- .gitignore
- src/bindings/bnd_defines.cpp
- src/pysrc/setup.py
Wrapping ON::UnitScale makes it easy to get the scale factor between
the different length unit systems so that it stays consistent with Rhino.
> Wrap ON::UnitScale

- src/bindings/bnd_mesh.h
- src/bindings/bnd_nurbscurve.cpp
* Mesh needed proper function signature for getter functions to static, readonly properties
* Expose NurbsCurve Points and Knots accessors.
> Fixups for Mesh and NurbsCurve

- src/bindings/bnd_extensions.cpp
JavaScript support for `File3dm.materials()`, following the implementation of `File3dm.layers()`
/cc @fraguada
> Wrap file material table for js

- docs/javascript/RHINO3DM-BUILD.JS.md
Use WSL so we only need one set of instructions for macOS, Linux and Windows
Fixes RH3DM-30
> Update js compile guide to include windows

- src/docgen/JavascriptClass.cs
Added the following to the typescript declarations generator:
**Default promise export**
`export default function rhino3dm() : Promise<RhinoModule>;`
This allows typescript to access the library nearly the same was as the examples:
```javascript
import rhino3dm from 'rhino3dm'
let rhino:RhinoModule;
rhino3dm().then(r:RhinoModule => {
rhino = r;
}
```
**RhinoModule class**
Contains helper property declarations that allow typescript to access declared rhinocommon classes with the module above.
**Constructors, where applicable**
If a rhino3dmjs class in newable, declare a `constructor()` from `jsclass.Constructors`
> typescript generation enchancement

- src/docgen/JavascriptClass.cs
Two small fixes:
**Enums in parent module**
Enums could not be referenced outside of the rhino module. Change allows their use with the following syntax:
```javascript
import rhino3dm, { RhinoModule } from 'rhino3dm'
let rhino: RhinoModule;
rhino3dm().then(r:RhinoModule => {
rhino = r;
}
let crv = new rhino.ArcCurve();
if (crv.ObjectType == rhino.ObjectType.Curve) {
// Do something
}
```
**Catch straggling C# types**
Some C# types were getting through the `ToTypeScriptType()` check. The additions here catch all the ones in the current file.
> typescript generator fix: enums and C# types

- src/rhino3dm/__init__.py
As per https://github.com/asottile/flake8-2020
The next version of python after 3.9 could be python 4.0, in which case the python 3 code should run, not python 2.  Alpha versions may come out in 2020 so this will come around pretty quickly.
> Improved version check py2 vs py3

- src/bindings/bnd_instance.cpp
- src/bindings/bnd_instance.h
- src/bindings/bnd_uuid.cpp
- src/bindings/bnd_uuid.h
Fixes #126 / RH3DM-55
It is currently not possible to read the Name, Id or the child objects of an InstanceDefinition from the .3dm file. The PR exposes the necessary variables and adds two functions to do so.
*exposes BND_InstanceDefinitionGeometry.Name and .Id
*implements BND_InstanceDefinitionGeometry.GetObjectIds() to return a std::vector<BND_UUID> containing the IDs of all child objects, that can be passed on by pybind
*to do so, the PR adds a converter to bnd_uuid.h/cpp that converts from ON_SimpleArray<ON_UUID> to std::vector<BND_UUID>
> implements BND_InstanceDefinitionGeometry.GetObjectIds(), exposes .Name and .Id

- src/bindings/bnd_xform.cpp
- src/bindings/bnd_xform.h
Adresses #128 / RH3DM-56
changed from previous pull request to return flat BND_TUPLE containing the transformation matrix in either row- or column major order.
> implements BND_Transform.ToFloatArray()

- .circleci/config.yml
- appveyor.yml
Use Python 3.8 (latest) on Linux and Windows and Python 3.7 (default for Catalina) on macOS
> Update Python CI builds

- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
Proposes new method BND_ONXModel_ObjectTable::FindId(BND_UUID id) to fetch an individual FileObject by its Guid from the ObjectTable (equivalent to rhinocommons ObjectTable.FindId ).
Let me know if you would want to break this up into several functions. It would be helpful to have this implemented to not have to loop through the objects in python code just to find a single object.
> feature: BND_ONXModel_ObjectTable::FindId(id)

- src/bindings/bnd_xform.cpp
BND_Transform.ToFloatArray() was implemented by https://github.com/mcneel/rhino3dm/commit/fb1f27e20c6a55925214bfca69f17d290f554eb5 for Python but not for JavaScript.
Resolves #159
> Add JS binding for BND_Transform.ToFloatArray()

- .gitignore
- docs/python/RHINO3DM-BUILD.PY.md
- setup.py
This PR makes `pip install -e .` work. This way, it's possible to install an editable version of the package (ie. a link to the `/src/rhino3dm` folder in the installed packages of the current python), and changes to the python source will be picked up immediately.
Changes to the C++ source are seen after a rebuild (`python setup.py develop`); that rebuild is faster than building a binary distribution because it does not use a new temporary build folder each time (it builds in /build/temp.system).
> Fix setup.py for pip install -e . command

- src/bindings/bnd_nurbscurve.cpp
- src/bindings/bnd_nurbscurve.h
- src/bindings/bnd_nurbssurface.cpp
- src/bindings/bnd_nurbssurface.h
This PR has a couple related things in it about knots and CVs for curves and surfaces, and works on Python but not on WASM. Let me know if there is something to do to have the same features on both platforms and I'll correct as needed.
1. For surfaces, add bindings to get and set the knots and CVs. These are modeled on the curve bindings, but but since the CV list is 2-dimensional for a surface, the getter/setter accepts a tuple of indices that works nicely through pybind: `srf.Points[1,2]`. Not sure how to make this work in WASM.
2. For curves and surfaces, add bounds checking to knots and CVs g/setters. This makes the collections proper iterables in Python, and things like `for k in srf.KnotsU:` work (without the bounds checking, that crashes Python). Maybe there should be a way to …
> Add bindings to access knots and CVs of a surface, and improve Python bindings for curves knots and CVs

- docs/javascript/RHINO3DM-BUILD.JS.md
- script/bootstrap.py
- script/build.py
- script/cibuild.py
- script/setup.py
_scripts/bootstrap.py_
_scripts/setup.py_
and
_script/build.py_
now support javascript build targets.
This reproduces - and improves upon - the _src/build_javascript.py_ which should be phased out.
Cite #183
> Javascript build support

- Current Development Tools.md
- script/bootstrap.py
- script/build.py
- script/setup.py
- src/ios.toolchain.cmake
- src/librhino3dmio_native/CMakeLists.txt
macOS build target CMake conversion.  librhino3dm_native is now generated using cmake and the build script is converted.
iOS support in progress
> macOS build target CMake conversion

- script/bootstrap.py
On Amazon Linux 2, a useable version of cmake can be installed via `sudo yum install cmake3`. The build scripts look for `cmake` so I created a symlink to get around this. Unfortunately `cmake --version` still returns `cmake3 version 3.13.1`, hence this ~~hack~~ change.
> Parse cmake version on amazon linux 2

- src/dotnet/Properties/AssemblyInfo.cs
- src/dotnet/Rhino3dm.core.csproj
- src/dotnet/build/net46/Rhino3dm.props
- src/dotnet/rhino/rhinosdkfont.cs
Make sure the native libraries are in the correct directories.
* src/build/windows/win64/Release/librhino3dm_native.dll
* src/build/linux/Release/librhino3dm_native.so
* src/build/macos/Release/librhino3dm_native.dylib
Then build the .NET library for .NET Standard 2.0 and .NET Framework 4.6.
```
msbuild src/dotnet/Rhino3dm.core.csproj -restore -t:Rebuild -p:Configuration=Release
```
Finally package it all up.
```
msbuild src/dotnet/Rhino3dm.core.csproj -restore -t:Pack -p:Configuration=Release
```
> Use Rhino3dm.core.csproj to build multi-targeting nuget package

- .circleci/config.yml
- script/build.py
- src/build_dotnet.py
@dbelcher I just noticed that build_dotnet.py was masking build errors, so I updated the linux dot builds to use the new scripts and updated the amazon linux docker image too.
> Use new scripts for linux dotnet CI builds

- src/bindings/bnd_point.cpp
- src/bindings/bnd_point.h
This new constructor will make the following possible...
```
from rhino3dm import Plane, Interval, PlaneSurface
srf = PlaneSurface(Plane.WorldXY(), Interval(-1,1), Interval(-2,3))
```
> Add Interval(double, double) constructor in python

- .circleci/config.yml
- Current Development Tools.md
* Updates circleci build to use `emscripten/emsdk:2.0.10` docker image to build rhino3dm.js
* Adds rhino3dm.js and rhino3dm.wasm to build artifacts
> Use emscripten v2.0.10 (latest)

- .devcontainer.json
- docs/javascript/RHINO3DM-BUILD.JS.md
See [readme](https://github.com/mcneel/rhino3dm/blob/will/devcontainer/docs/javascript/RHINO3DM-BUILD.JS.md#dev-container)...
> Add dev container config to project to make rhino3dm.js development easier

- src/bindings/bnd_draco.cpp
Colour values (stored as `draco::DT_UINT8`) were being normalised during conversion to `char` which resulted in invalid colours.
See https://discourse.mcneel.com/t/create-three-js-mesh-from-rhino-with-vertex-colors/120239
> Get correct vertex colours during draco decode

- src/bindings/bnd_extensions.cpp
It should fix the memory corruption in the toByteArray function called from javascript.
**Error**
The previous approach just created a view on the buffer that is owned by the `ON_Write3dmBufferArchive` class. At the end of the `ToByteArray2` function the memory is freed by the owner. So it was the question of luck if it works or not.
**Solution**
Now I create a new buffer for the result, and copy the original buffer content to it. Returning of this value is somewhat cleaner than the original solution. To be honest it introduces another problem: Who will free this memory up? I don't have a solution for that right now (maybe another function that should be called when the buffer is not needed anymore), but at least now it works as expected.
**Fixes**
- Sure:
- …
> Fix ToByteArray memory corruption.

- docs/javascript/RHINO3DM-BUILD.JS.md
- script/bootstrap.py
- script/build.py
- script/setup.py
- src/CMakeLists.txt
While I was trying to compile rhino3dm.js on Windows I've struggled with some things in the script.
This pull request contains my modifications to make it work on Windows:
- Extended the build instructions in the readme.
- Fixed Emscripten version detection.
- When using `subprocess.Popen` the shell parameter must be true so the subprocess will inherit environment variables. I modified it only on Windows, because it is usually a source of platform specific errors.
- Use `emmake` helper to build with Emscripten so the `make` tool shouldn't be in the PATH.
- The call `shlex.split` must have the posix parameter set to false on Windows.
> Make Emscripten build work on Windows

- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
- src/bindings/bnd_point.cpp
I had to add some functionality to complete support of mesh texture coordinates:
- The javascript build was missing a binding for 2fPoint.
- Added the Add function for mesh texture coordinates. Similar to the vertex and normal list.
Please let me know if I'm forgetting something or if I need to update any documentation.
Tested it on my end with rhino-compute.
> Add support for mesh texture coordinates.

- src/bindings/bnd_instance.cpp
- src/bindings/bnd_instance.h
This change adds the [SourceArchive](https://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_DocObjects_InstanceDefinition_SourceArchive.htm) and [UpdateType](https://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_DocObjects_InstanceDefinition_UpdateType.htm) properties to the [InstanceDefinition](https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_DocObjects_InstanceDefinition.htm) bindings. It also exposes the [InstanceDefinitionUpdateType](https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_DocObjects_InstanceDefinitionUpdateType.htm) enum.
Together, these properties allow rhino3dm users to load geometries from linked instance definitions by finding and opening the linked file.
---
Closes #367
> Add support for reading linked instance definitions

- .github/workflows/ci_workflow.yml
- src/bindings/bnd_3dm_settings.cpp
- src/bindings/bnd_extensions.cpp
Fixes #303. 
The property name `count` for doc.strings().count() was used twice, once for doc.strings().count() and then used again for doc.strings().documentUserTextCount(). Fixed by adding `documentUserTextCount` as the property name.
> Bindings: Fix doc.strings().count() property for js

- docs/javascript/RHINO3DM.JS.md
Adding instruction to get rhino3dm working with React.js
> Add react instructions

- src/bindings/.editorconfig
This pull request adds an `.editorconfig` file to the `src/bindings` folder so newcomers like me will be less likely to ignorantly plow through the project's indentation convention in the future.
> Add .editorconfig

- src/bindings/bnd_point.cpp
- src/bindings/bnd_point.h
This pull request exposes the `==` and `!=` operators to Python for the following types:
- Interval
- Point2d
- Point2f
- Point3d
- Point3f
- Point4d
- Vector2d
- Vector3d
- Vector3f
> Expose equality operators on point, vector, and interval types

- src/bindings/bnd_mesh.cpp
- src/bindings/bnd_mesh.h
Explicit __iter__ implementations in bnd_mesh were broken, only yielding n-1 items. However, just having a __getitem__ method is enough for python to iterate over things, and the resulting behavior is correct.
> Remove __iter__ implementations in mesh bindings

- setup.py
* Ensure building of universal binary of library for MacOS
* Use modern path and file idioms
* Don't os.chdir, that can leave host in unknown state
* Use subprocess for safer control, use cwd parameter to it
> Universal builds on Mac and setup.py clean-up

- script/bootstrap.py
- src/bindings/bnd_annotationbase.cpp
- src/bindings/bnd_annotationbase.h
- src/bindings/bnd_defines.cpp
- src/bindings/bnd_dimensionstyle.cpp
- src/bindings/bnd_dimensionstyle.h
- src/bindings/bnd_object.cpp
- src/bindings/bnd_plane.cpp
- src/bindings/bnd_plane.h
- src/bindings/bnd_point.cpp
* annotation type
* arrow head types
* arrow head points
* different annotation types
* Points/points: give 3d points for the given annotation. These are
returned in dictionaries with string keys that describe what the
points are used for. The naming is based on the C++ signature
* GetDisplayLines/getDisplayLines: give lines, arcs etc for
the given annotation. These are returned in a dictionary with
entries "lines", "arcs" where it makes sense
* added some API to other types where it supports the reading of
annotations, including dimstyle, vector and plane API expansion.
The API additions are for both Python and JavaScript.
> Wrap annotation-related API

- src/js/rhino3dm.d.ts
The TypeScript bindings are not reflecting the actual argument order for the `add` method in `File3dmObjectTable`.
> Swap order of "add" arguments.

- src/js/rhino3dm.d.ts
Opening this in case someone else has run afoul of this with typescript.
At runtime, after transpiling a Jupyter widget that uses `rhino3dm.js`, I was getting the following error:
```
22:18:49.603 Error loading Rhino file: 
message: "function File3dm.fromByteArray called with 2 arguments, expected 1 args!"​
name: "BindingError"
stack: "BindingError: function File3dm.fromByteArray called with 2 arguments, expected 1 args!\n./node_modules/rhino3dm/rhino3dm.js/rhino3dm/extendError/errorClass<@http://localhost:8888/lab/extensions/rhino-inside-jupyter/static/vendors-node_modules_rhino3dm_rhino3dm_js.11d87ae55439add75335.js:755:79097\nBindingError@http://localhost:8888/lab/extensions/rhino-inside-jupyter/static/vendors-
```
This was fixed in my program when I modified the `rhino3dm.d.ts` file …
> [JS] fix: type mismatch in fromByteArray: File3dm

- src/bindings/bnd_extensions.cpp
- tests/python/test_File3dm_ObjectTable.py
Add support for negative indexing in `File3dmObjectTable` as discussed in #651.
Tests have been added as well.
> [Python] Add support for negative indexing in ObjectTable

- CHANGELOG.md
- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
- tests/python/test_File3dm_ObjectTable.py
Adds three additional overloads of `AddPoint` for Python, mirroring the existing `AddPoint1`, `AddPoint2` and `AddPoint4` which 
do not take object attributes.
Minimal tests have been added.
Bindings have been added to Python only.
Implements #664.
> [Python] AddPoint with attributes

- CHANGELOG.md
- src/bindings/bnd_extensions.cpp
- src/bindings/bnd_extensions.h
- tests/python/test_File3dm_ObjectTable.py
Add one additional overload of `AddLine` for Python, mirroring the existing `AddLine1` which do not take object attributes.
Minimal tests have been added.
Binding has been added to Python only.
Based on #665, which should be merged first .
> [Python] AddLine with attributes
